"""empty message

Revision ID: 3e9c634f696e
Revises: 977f5e7c242e
Create Date: 2022-11-28 21:37:52.815424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c634f696e'
down_revision = '977f5e7c242e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sessions_session_id_key', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('unique_rowid()'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry', sa.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.create_index('sessions_session_id_key', 'sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###
