"""empty message

Revision ID: 977f5e7c242e
Revises: d3574b8bc75b
Create Date: 2022-11-23 16:30:21.302949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977f5e7c242e'
down_revision = 'd3574b8bc75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
