"""empty message

Revision ID: d3574b8bc75b
Revises: 5129421125e1
Create Date: 2022-11-16 22:39:10.030639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3574b8bc75b'
down_revision = '5129421125e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_data', sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('meta_data', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_data', sa.Column('date', sa.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('meta_data', 'updated')
    # ### end Alembic commands ###
